// <auto-generated />
using System;
using Avansist.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Avansist.DAL.Migrations
{
    [DbContext(typeof(AvansistDbContext))]
    [Migration("20211004204045_Inicial")]
    partial class Inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Avansist.Models.Entities.Agenda", b =>
                {
                    b.Property<int>("AgendaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EmpleadoEncargado")
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FechaFinEvento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicioEvento")
                        .HasColumnType("datetime2");

                    b.Property<string>("HoraFinEvento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoraInicioEvento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreEvento")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NumeroDocumento")
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("AgendaId");

                    b.ToTable("Agendas");
                });

            modelBuilder.Entity("Avansist.Models.Entities.AgendaBeneficiario", b =>
                {
                    b.Property<int>("AgendaBeneficiarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EmpleadoEncargado")
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("FechaFinEvento")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaInicioEvento")
                        .HasColumnType("date");

                    b.Property<string>("NombreEvento")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NumeroDocumento")
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("PreinscripcionId")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("AgendaBeneficiarioId");

                    b.HasIndex("PreinscripcionId");

                    b.ToTable("AgendaBeneficiarios");
                });

            modelBuilder.Entity("Avansist.Models.Entities.ControlAsistencia", b =>
                {
                    b.Property<int>("ControlAsistenciaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AutorizacionSalida")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaSalida")
                        .HasColumnType("date");

                    b.Property<string>("ObservacionIngreso")
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ObservacionSalida")
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PreinscripcionId")
                        .HasColumnType("int");

                    b.HasKey("ControlAsistenciaId");

                    b.HasIndex("PreinscripcionId");

                    b.ToTable("ControlAsistencias");
                });

            modelBuilder.Entity("Avansist.Models.Entities.DetalleSalida", b =>
                {
                    b.Property<int>("DetalleSalidaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AutorizacionSalidaExtracurricular")
                        .HasColumnType("bit");

                    b.Property<int>("PreinscripcionId")
                        .HasColumnType("int");

                    b.Property<int>("SalidaExtracurricularId")
                        .HasColumnType("int");

                    b.HasKey("DetalleSalidaId");

                    b.HasIndex("PreinscripcionId");

                    b.HasIndex("SalidaExtracurricularId");

                    b.ToTable("DetalleSalidas");
                });

            modelBuilder.Entity("Avansist.Models.Entities.Estado", b =>
                {
                    b.Property<int>("EstadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NombreEstado")
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("EstadoId");

                    b.ToTable("Estados");
                });

            modelBuilder.Entity("Avansist.Models.Entities.Etnia", b =>
                {
                    b.Property<int>("EtniaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NombreEtnia")
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("EtniaId");

                    b.ToTable("Etnias");
                });

            modelBuilder.Entity("Avansist.Models.Entities.Genero", b =>
                {
                    b.Property<int>("GeneroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NombreGenero")
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("GeneroId");

                    b.ToTable("Generos");
                });

            modelBuilder.Entity("Avansist.Models.Entities.GrupoSanguineo", b =>
                {
                    b.Property<int>("GrupoSanguineoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Rh")
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("GrupoSanguineoId");

                    b.ToTable("GrupoSanguineos");
                });

            modelBuilder.Entity("Avansist.Models.Entities.Jornada", b =>
                {
                    b.Property<int>("JornadaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NombreJornada")
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("JornadaId");

                    b.ToTable("Jornadas");
                });

            modelBuilder.Entity("Avansist.Models.Entities.Modalidad", b =>
                {
                    b.Property<int>("ModalidadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NombreModalidad")
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("ModalidadId");

                    b.ToTable("Modalidads");
                });

            modelBuilder.Entity("Avansist.Models.Entities.Padrino", b =>
                {
                    b.Property<int>("PadrinoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ApellidoPadrino")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CorreoElectronico")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NombrePadrino")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NumeroDocumento")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Ocupacion")
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("TipoDocumentoId")
                        .HasColumnType("int");

                    b.HasKey("PadrinoId");

                    b.HasIndex("TipoDocumentoId");

                    b.ToTable("Padrinos");
                });

            modelBuilder.Entity("Avansist.Models.Entities.Preinscripcion", b =>
                {
                    b.Property<int>("PreinscripcionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AntecedenteMedico")
                        .HasColumnType("bit");

                    b.Property<bool>("AntecedentePsicologico")
                        .HasColumnType("bit");

                    b.Property<string>("ApellidoAcudiente")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ApellidoMadre")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ApellidoPadre")
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("AporteEconomicoPadrino")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BarrioAcudiente")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BarrioMadre")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BarrioPadre")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CustodiaBeneficiario")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("DescripcionEnfermedad")
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DescripcionPsicologica")
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DireccionAcudiente")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DireccionMadre")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DireccionPadre")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DireccionResidencia")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Edad")
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("EstadoId")
                        .HasColumnType("int");

                    b.Property<int>("EtniaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaMatricula")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("date");

                    b.Property<DateTime>("FechaRetiro")
                        .HasColumnType("date");

                    b.Property<int>("GeneroId")
                        .HasColumnType("int");

                    b.Property<int>("GrupoSanguineoId")
                        .HasColumnType("int");

                    b.Property<string>("GrupoSisben")
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("IngresoEconomicoAcudiente")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IngresoEconomicoMadre")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IngresoEconomicoPadre")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("InstitucionEducativa")
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("JornadaId")
                        .HasColumnType("int");

                    b.Property<string>("LugarExpedicionDocumento")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LugarExpedicionDocumentoAcudiente")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LugarExpedicionDocumentoMadre")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LugarExpedicionDocumentoPadre")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LugarNacimiento")
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ModalidadId")
                        .HasColumnType("int");

                    b.Property<string>("Municipio")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MunicipioAcudiente")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MunicipioMadre")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MunicipioPadre")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NivelEscolaridad")
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("NivelEscolaridadAcudiente")
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("NivelEscolaridadMadre")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NivelEscolaridadPadre")
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("NombreAcudiente")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NombreEps")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NombreMadre")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NombrePadre")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NumeroDocumento")
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("NumeroDocumentoAcudiente")
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("NumeroDocumentoMadre")
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("NumeroDocumentoPadre")
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ObservacionRetiro")
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("OcupacionAcudiente")
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("OcupacionMadre")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OcupacionPadre")
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PadrinoId")
                        .HasColumnType("int");

                    b.Property<string>("PrimerApellidoBeneficiario")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PrimerNombreBeneficiario")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SegundoApellidoBeneficiario")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SegundoNombreBeneficiario")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TallaCamisa")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TallaPantalon")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TallaZapatos")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TelefonoAcudiente")
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("TelefonoMadre")
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("TelefonoPadre")
                        .HasColumnType("nvarchar(45)");

                    b.Property<int>("TipoDocumentoId")
                        .HasColumnType("int");

                    b.HasKey("PreinscripcionId");

                    b.HasIndex("EstadoId");

                    b.HasIndex("EtniaId");

                    b.HasIndex("GeneroId");

                    b.HasIndex("GrupoSanguineoId");

                    b.HasIndex("JornadaId");

                    b.HasIndex("ModalidadId");

                    b.HasIndex("PadrinoId");

                    b.HasIndex("TipoDocumentoId");

                    b.ToTable("Preinscripcions");
                });

            modelBuilder.Entity("Avansist.Models.Entities.SalidaExtracurricular", b =>
                {
                    b.Property<int>("SalidaExtracurricularId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AgendaId")
                        .HasColumnType("int");

                    b.HasKey("SalidaExtracurricularId");

                    b.HasIndex("AgendaId");

                    b.ToTable("SalidaExtracurriculars");
                });

            modelBuilder.Entity("Avansist.Models.Entities.TipoDocumento", b =>
                {
                    b.Property<int>("TipoDocumentoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NombreTipoDocumento")
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("TipoDocumentoId");

                    b.ToTable("TipoDocumentos");
                });

            modelBuilder.Entity("Avansist.Models.Entities.AgendaBeneficiario", b =>
                {
                    b.HasOne("Avansist.Models.Entities.Preinscripcion", "Preinscripcion")
                        .WithMany("AgendaBeneficiarios")
                        .HasForeignKey("PreinscripcionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Preinscripcion");
                });

            modelBuilder.Entity("Avansist.Models.Entities.ControlAsistencia", b =>
                {
                    b.HasOne("Avansist.Models.Entities.Preinscripcion", "Preinscripcion")
                        .WithMany("ControlAsistencias")
                        .HasForeignKey("PreinscripcionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Preinscripcion");
                });

            modelBuilder.Entity("Avansist.Models.Entities.DetalleSalida", b =>
                {
                    b.HasOne("Avansist.Models.Entities.Preinscripcion", "Preinscripcion")
                        .WithMany("DetalleSalidas")
                        .HasForeignKey("PreinscripcionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Avansist.Models.Entities.SalidaExtracurricular", "SalidaExtracurricular")
                        .WithMany("DetalleSalidas")
                        .HasForeignKey("SalidaExtracurricularId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Preinscripcion");

                    b.Navigation("SalidaExtracurricular");
                });

            modelBuilder.Entity("Avansist.Models.Entities.Padrino", b =>
                {
                    b.HasOne("Avansist.Models.Entities.TipoDocumento", "TipoDocumento")
                        .WithMany("Padrino")
                        .HasForeignKey("TipoDocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoDocumento");
                });

            modelBuilder.Entity("Avansist.Models.Entities.Preinscripcion", b =>
                {
                    b.HasOne("Avansist.Models.Entities.Estado", "Estado")
                        .WithMany("Preinscripcions")
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Avansist.Models.Entities.Etnia", "Etnia")
                        .WithMany("Preinscripcions")
                        .HasForeignKey("EtniaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Avansist.Models.Entities.Genero", "Genero")
                        .WithMany("Preinscripcions")
                        .HasForeignKey("GeneroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Avansist.Models.Entities.GrupoSanguineo", "GrupoSanguineo")
                        .WithMany("Preinscripcions")
                        .HasForeignKey("GrupoSanguineoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Avansist.Models.Entities.Jornada", "Jornada")
                        .WithMany("Preinscripcions")
                        .HasForeignKey("JornadaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Avansist.Models.Entities.Modalidad", "Modalidad")
                        .WithMany("Preinscripcions")
                        .HasForeignKey("ModalidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Avansist.Models.Entities.Padrino", "Padrino")
                        .WithMany("Preinscripcions")
                        .HasForeignKey("PadrinoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Avansist.Models.Entities.TipoDocumento", "TipoDocumento")
                        .WithMany("Preinscripcions")
                        .HasForeignKey("TipoDocumentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Estado");

                    b.Navigation("Etnia");

                    b.Navigation("Genero");

                    b.Navigation("GrupoSanguineo");

                    b.Navigation("Jornada");

                    b.Navigation("Modalidad");

                    b.Navigation("Padrino");

                    b.Navigation("TipoDocumento");
                });

            modelBuilder.Entity("Avansist.Models.Entities.SalidaExtracurricular", b =>
                {
                    b.HasOne("Avansist.Models.Entities.Agenda", "Agenda")
                        .WithMany()
                        .HasForeignKey("AgendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agenda");
                });

            modelBuilder.Entity("Avansist.Models.Entities.Estado", b =>
                {
                    b.Navigation("Preinscripcions");
                });

            modelBuilder.Entity("Avansist.Models.Entities.Etnia", b =>
                {
                    b.Navigation("Preinscripcions");
                });

            modelBuilder.Entity("Avansist.Models.Entities.Genero", b =>
                {
                    b.Navigation("Preinscripcions");
                });

            modelBuilder.Entity("Avansist.Models.Entities.GrupoSanguineo", b =>
                {
                    b.Navigation("Preinscripcions");
                });

            modelBuilder.Entity("Avansist.Models.Entities.Jornada", b =>
                {
                    b.Navigation("Preinscripcions");
                });

            modelBuilder.Entity("Avansist.Models.Entities.Modalidad", b =>
                {
                    b.Navigation("Preinscripcions");
                });

            modelBuilder.Entity("Avansist.Models.Entities.Padrino", b =>
                {
                    b.Navigation("Preinscripcions");
                });

            modelBuilder.Entity("Avansist.Models.Entities.Preinscripcion", b =>
                {
                    b.Navigation("AgendaBeneficiarios");

                    b.Navigation("ControlAsistencias");

                    b.Navigation("DetalleSalidas");
                });

            modelBuilder.Entity("Avansist.Models.Entities.SalidaExtracurricular", b =>
                {
                    b.Navigation("DetalleSalidas");
                });

            modelBuilder.Entity("Avansist.Models.Entities.TipoDocumento", b =>
                {
                    b.Navigation("Padrino");

                    b.Navigation("Preinscripcions");
                });
#pragma warning restore 612, 618
        }
    }
}
